# Generated by Django 4.1 on 2022-09-02 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Избран пользователями'),
        ),
    ]
